#!/usr/bin/env bash
#dsf# sr/bin/env bash


echo "WELCOME TO ARTEMIS ENGINE DESIGN PROGRAM"
echo "Starting Calculations..."
#TODO: Insert password protection
#sleep 1s
echo "---isentropic calculations---"
echo "calculating engine designs"
python ./bin/one.py
echo "graphing engine performance"
#echo "calculating abstract engine theoretics"
#python ./bin/two.py




echo "Process Terminated"

